#!/usr/bin/env python3
"""
Claude PR Reviewer - Automatically reviews pull requests using the Claude API
and posts feedback as GitHub comments.
"""

import os
import json
from anthropic import Anthropic
from github import Github

def get_pr_diff(gh_client, repo_owner, repo_name, pr_number):
    """Fetch the diff for a pull request."""
    repo = gh_client.get_repo(f"{repo_owner}/{repo_name}")
    pr = repo.get_pull(pr_number)
    
    # Get all commits in the PR
    commits = pr.get_commits()
    
    # Build diff content
    diff_content = f"# PR #{pr_number}: {pr.title}\n\n"
    diff_content += f"**Author:** {pr.user.login}\n"
    diff_content += f"**Description:** {pr.body or '(No description provided)'}\n\n"
    diff_content += "## Changed Files\n\n"
    
    files = pr.get_files()
    total_changes = 0
    
    for file in files:
        if file.changes > 0:  # Only include changed files
            diff_content += f"### {file.filename} ({file.changes} changes)\n"
            diff_content += f"- **Additions:** {file.additions}\n"
            diff_content += f"- **Deletions:** {file.deletions}\n\n"
            
            if file.patch:
                diff_content += f"```diff\n{file.patch}\n```\n\n"
            
            total_changes += file.changes
    
    return diff_content, pr, total_changes


def review_code_with_claude(diff_content, total_changes):
    """Use Claude to review the PR diff."""
    client = Anthropic()
    
    system_prompt = """You are an expert code reviewer. Analyze the provided pull request diff and provide:

1. **Summary**: A brief overview of what changes were made
2. **Strengths**: What's good about this code
3. **Issues Found**: Any bugs, security concerns, performance issues, or code quality problems (if none, say so)
4. **Suggestions**: Specific recommendations for improvement
5. **Rating**: A brief assessment (e.g., "Looks good to merge", "Needs minor fixes", "Needs significant changes")

Be constructive, specific, and actionable. Focus on:
- Code correctness and potential bugs
- Security vulnerabilities
- Performance concerns
- Code style and maintainability
- Testing adequacy (if visible)

Format your response as clear sections with markdown. Be concise but thorough."""

    user_message = f"""Please review this pull request:

{diff_content}

Total lines changed: {total_changes}"""

    message = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=2000,
        system=system_prompt,
        messages=[
            {"role": "user", "content": user_message}
        ]
    )
    
    return message.content[0].text


def post_review_comment(gh_client, repo_owner, repo_name, pr_number, review_text):
    """Post the Claude review as a GitHub comment."""
    repo = gh_client.get_repo(f"{repo_owner}/{repo_name}")
    pr = repo.get_pull(pr_number)
    
    # Format the comment with a bot header
    comment_body = f"""## 🤖 Claude Code Review

{review_text}

---
*This review was automatically generated by Claude. Please review and use your judgment when applying suggestions.*"""
    
    pr.create_issue_comment(comment_body)
    print(f"✅ Posted review comment to PR #{pr_number}")


def main():
    # Get environment variables
    api_key = os.getenv("ANTHROPIC_API_KEY")
    github_token = os.getenv("GITHUB_TOKEN")
    pr_number = int(os.getenv("PR_NUMBER"))
    repo_owner = os.getenv("REPO_OWNER")
    repo_name = os.getenv("REPO_NAME")
    
    if not all([api_key, github_token, pr_number, repo_owner, repo_name]):
        print("❌ Missing required environment variables")
        return
    
    print(f"🔍 Reviewing PR #{pr_number} in {repo_owner}/{repo_name}...")
    
    # Initialize GitHub client
    gh_client = Github(github_token)
    
    try:
        # Fetch PR diff
        print("📥 Fetching PR diff...")
        diff_content, pr, total_changes = get_pr_diff(gh_client, repo_owner, repo_name, pr_number)
        
        if total_changes == 0:
            print("⏭️  No changes found in PR, skipping review")
            return
        
        print(f"📊 Found {total_changes} lines changed across {len(list(pr.get_files()))} files")
        
        # Get Claude's review
        print("🤔 Getting Claude's review...")
        review_text = review_code_with_claude(diff_content, total_changes)
        
        # Post the review
        print("📤 Posting review to GitHub...")
        post_review_comment(gh_client, repo_owner, repo_name, pr_number, review_text)
        
        print("✨ Review complete!")
        
    except Exception as e:
        print(f"❌ Error during review: {str(e)}")
        raise


if __name__ == "__main__":
    main()